name: CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches: 
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update Path
      run: echo "::add-path::$RUNNER_WORKSPACE/$(basename $GITHUB_REPOSITORY)" # Make it accessible from runner
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Install solc
      run: |
        set -x
        wget -c https://github.com/ethereum/solidity/releases/download/v0.5.12/solc-static-linux
        mv solc-static-linux solc
        chmod +x solc
        solc --version
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    - name: Generate genesis file
      run: bash generate.sh 15001 heimdall-15001
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    # - name: Run tests
    #   run: npm run test:ci
    #   env:
    #     ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
